services:
  jetson-dfl:
    build:
      context: ./docker
      dockerfile: Dockerfile
      args:
        L4T_TAG: "r36.2.0"
        HOST_UID: "${UID}"
        HOST_GID: "${GID}"

    runtime: nvidia
    platform: linux/arm64
    network_mode: host
    privileged: true
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,video
      - TZ=Europe/Paris
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
#      - ${HOME}:${HOME}
      - /workspace:/workspace

    working_dir: ${HOME}
    shm_size: "8gb"
    stdin_open: true
    tty: true
    command: bash

